# The commented lines below come from the RESILIENCY branch for Zipkin & Sleuth.

#spring:
#  sleuth:
#    sampler:
#      percentage: 1.0
#  zipkin:
#    baseUrl: ${vcap.services.zipkin-server.credentials.uri:http://localhost:9411}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fjgalindosan/refarch-cloudnative-spring-config

server:
  port: ${PORT:8888}

management:
  context-path: /admin

eureka:
  client:
    serviceUrl:
       defaultZone: ${vcap.services.eureka-service-discovery.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    preferIpAddress: true

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: false
